"""Tests for the offline quality-gated sleeve allocator (Lane M2).

Covers: (a) happy-path round-trip through the REAL
``ArtifactPortfolioModeStrategy`` consumer (the emitted manifest does NOT
fail-close); (b) fail-closed path parametrized over the consumer's enumerated
reason codes; (c) allocation math (quality gate, ERC weight sum/cap,
determinism, graceful None/empty handling); (d) byte-golden manifest
serialization.

All synthetic return streams are generated by a deterministic linear
congruential generator (no numpy RNG, no scipy) so every test is bit-for-bit
reproducible. ASCII only.
"""

from __future__ import annotations

import copy
import hashlib
import importlib.util
import json
import sys
from pathlib import Path
from types import SimpleNamespace
from typing import Any
from collections.abc import Callable

import pytest

from lumina_quant.portfolio.quality_gated_allocation import (
    allocate_quality_gated,
    build_allocation_manifest,
    compute_sleeve_quality,
)

MODULE_PATH = (
    Path(__file__).resolve().parents[2]
    / "src"
    / "lumina_quant"
    / "strategies"
    / "artifact_portfolio_mode.py"
)
_SPEC = importlib.util.spec_from_file_location(
    "artifact_portfolio_mode_for_quality_gated_allocation_tests", MODULE_PATH
)
ARTIFACT_PORTFOLIO_MODE = importlib.util.module_from_spec(_SPEC)
assert _SPEC is not None and _SPEC.loader is not None
sys.modules[_SPEC.name] = ARTIFACT_PORTFOLIO_MODE
_SPEC.loader.exec_module(ARTIFACT_PORTFOLIO_MODE)


def _lcg_stream(seed: int, n: int) -> list[float]:
    """Deterministic linear-congruential PRNG stream in [0, 1) (Numerical Recipes constants)."""
    x = seed
    values: list[float] = []
    for _ in range(n):
        x = (1664525 * x + 1013904223) % (2**32)
        values.append(x / (2**32))
    return values


def _synthetic_returns(seed: int, n: int, *, drift: float, scale: float) -> list[float]:
    return [(value - 0.5) * scale + drift for value in _lcg_stream(seed, n)]


def _sha256_of(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _single_sleeve_manifest(tmp_path: Path) -> dict[str, Any]:
    """A single strongly-positive-edge sleeve; the manifest must NOT fail-close."""
    source_path = tmp_path / "source.json"
    source_path.write_text(json.dumps({"ready": True}), encoding="utf-8")
    sleeves = {
        "sleeve_a": {
            "returns": _synthetic_returns(42, 64, drift=0.004, scale=0.01),
            "turnover": 0.0,
            "strategy_class": "MovingAverageCrossStrategy",
            "symbols": ["BTC/USDT"],
            "params": {"short_window": 4, "long_window": 12},
            "source_artifact_id": "src",
        }
    }
    source_artifacts = [
        {
            "id": "src",
            "path": str(source_path),
            "sha256": _sha256_of(source_path),
            "max_age_hours": 876_000,
            "ready": True,
            "portfolio_ready": True,
        }
    ]
    return build_allocation_manifest(sleeves, source_artifacts=source_artifacts, gross_cap=1.0)


def _write_manifest(tmp_path: Path, manifest: dict[str, Any], name: str) -> Path:
    path = tmp_path / f"{name}.json"
    path.write_text(json.dumps(manifest), encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# (a) Happy path: round-trip through the REAL consumer.
# ---------------------------------------------------------------------------


def test_manifest_round_trips_through_real_consumer_without_fail_closing(tmp_path: Path) -> None:
    manifest = _single_sleeve_manifest(tmp_path)
    manifest_path = _write_manifest(tmp_path, manifest, "manifest")

    definition = ARTIFACT_PORTFOLIO_MODE.resolve_portfolio_mode_definition(
        f"manifest:{manifest_path}"
    )

    assert "manifest_fail_closed_to_cash" not in definition.source_artifacts
    assert definition.cash_weight == 0.0
    assert [(c.component_id, c.weight, c.strategy_class) for c in definition.components] == [
        ("sleeve_a", 1.0, "MovingAverageCrossStrategy")
    ]


def test_manifest_constructs_the_real_strategy_and_stays_off_cash(tmp_path: Path) -> None:
    manifest = _single_sleeve_manifest(tmp_path)
    manifest_path = _write_manifest(tmp_path, manifest, "manifest")

    strategy = ARTIFACT_PORTFOLIO_MODE.ArtifactPortfolioModeStrategy(
        bars=SimpleNamespace(
            symbol_list=["BTC/USDT"], get_latest_bar_value=lambda *args, **kwargs: 100.0
        ),
        events=SimpleNamespace(put=lambda item: None),
        portfolio_mode=f"manifest:{manifest_path}",
    )

    assert strategy.definition.cash_weight != 1.0
    assert "manifest_fail_closed_to_cash" not in strategy.definition.source_artifacts
    assert [c.component_id for c in strategy.definition.components] == ["sleeve_a"]
    assert strategy.definition.components[0].weight == 1.0


# ---------------------------------------------------------------------------
# (b) Fail-closed path: parametrized over the consumer's enumerated reasons.
# ---------------------------------------------------------------------------


def _mutate(
    manifest: dict[str, Any], mutate_fn: Callable[[dict[str, Any]], None]
) -> dict[str, Any]:
    mutated = copy.deepcopy(manifest)
    mutate_fn(mutated)
    return mutated


_FAIL_CLOSED_CASES: dict[str, tuple[Callable[[dict[str, Any]], None], str]] = {
    "manifest_real_money_enabled": (
        lambda m: m.__setitem__("real_money_execution", True),
        "manifest_real_money_enabled",
    ),
    "manifest_oos_contaminated": (
        lambda m: m.__setitem__("uses_current_fold_oos", True),
        "manifest_oos_contaminated",
    ),
    "manifest_optimizer_provenance_invalid": (
        lambda m: m["optimizer_provenance"].__setitem__("selection_inputs", ["oos"]),
        "manifest_optimizer_provenance_invalid",
    ),
    "manifest_correlation_provenance_invalid": (
        lambda m: m["correlation_input_provenance"].__setitem__("ready", False),
        "manifest_correlation_provenance_invalid",
    ),
    "source_artifact_sha_mismatch": (
        lambda m: m["source_artifacts"][0].__setitem__("sha256", "0" * 64),
        "source_artifact_sha_mismatch:src",
    ),
    "source_artifact_freshness_missing": (
        lambda m: m["source_artifacts"][0].__setitem__("max_age_hours", 0),
        "source_artifact_freshness_missing:src",
    ),
    "manifest_children_empty": (
        lambda m: m.__setitem__("children", []),
        "manifest_children_empty",
    ),
    "child_current_fold_oos_provenance_missing": (
        lambda m: m["children"][0].__setitem__("no_current_fold_oos_provenance", False),
        "child_current_fold_oos_provenance_missing:sleeve_a",
    ),
    "child_train_validation_optimizer_provenance_missing": (
        lambda m: m["children"][0].__setitem__("train_validation_optimizer_provenance", False),
        "child_train_validation_optimizer_provenance_missing:sleeve_a",
    ),
    "child_real_money_enabled": (
        lambda m: m["children"][0].__setitem__("real_money_execution", True),
        "child_real_money_enabled:sleeve_a",
    ),
    "child_oos_contaminated": (
        lambda m: m["children"][0].__setitem__("uses_current_fold_oos", True),
        "child_oos_contaminated:sleeve_a",
    ),
    "child_optimizer_provenance_invalid": (
        lambda m: m["children"][0]["optimizer_provenance"].__setitem__("selection_inputs", ["oos"]),
        "child_optimizer_provenance_invalid:sleeve_a",
    ),
    "child_correlation_provenance_invalid": (
        lambda m: m["children"][0]["correlation_input_provenance"].__setitem__("ready", False),
        "child_correlation_provenance_invalid:sleeve_a",
    ),
    "child_source_unreconciled": (
        lambda m: m["children"][0].__setitem__("source_artifact_id", "does-not-exist"),
        "child_source_unreconciled:sleeve_a",
    ),
}


@pytest.mark.parametrize("case_name", sorted(_FAIL_CLOSED_CASES))
def test_induced_omission_fails_closed_to_cash(tmp_path: Path, case_name: str) -> None:
    manifest = _single_sleeve_manifest(tmp_path)
    mutate_fn, expected_reason = _FAIL_CLOSED_CASES[case_name]
    mutated = _mutate(manifest, mutate_fn)
    manifest_path = _write_manifest(tmp_path, mutated, case_name)

    definition = ARTIFACT_PORTFOLIO_MODE.resolve_portfolio_mode_definition(
        f"manifest:{manifest_path}"
    )

    assert definition.components == ()
    assert definition.cash_weight == 1.0
    assert definition.source_artifacts["manifest_fail_closed_to_cash"] == "true"
    assert definition.source_artifacts["manifest_fail_closed_reason"] == expected_reason


def test_missing_manifest_file_fails_closed_to_cash(tmp_path: Path) -> None:
    missing_path = tmp_path / "does-not-exist.json"

    definition = ARTIFACT_PORTFOLIO_MODE.resolve_portfolio_mode_definition(
        f"manifest:{missing_path}"
    )

    assert definition.components == ()
    assert definition.cash_weight == 1.0
    assert definition.source_artifacts["manifest_fail_closed_reason"] == "manifest_missing"


# ---------------------------------------------------------------------------
# (c) Allocation math.
# ---------------------------------------------------------------------------


def test_quality_gate_drops_the_negative_net_sharpe_sleeve() -> None:
    losing = _synthetic_returns(111, 64, drift=-0.02, scale=0.01)
    winning = _synthetic_returns(222, 64, drift=0.003, scale=0.01)

    quality_losing = compute_sleeve_quality(losing, 0.0)
    quality_winning = compute_sleeve_quality(winning, 0.0)
    assert quality_losing["net_sharpe"] < 0.0
    assert quality_winning["net_sharpe"] > 0.0

    weights = allocate_quality_gated(
        {"losing": losing, "winning": winning}, {"losing": 0.0, "winning": 0.0}
    )

    assert weights == {"winning": 1.0}


def test_erc_weights_sum_to_one_and_respect_upper_cap() -> None:
    low_vol = _synthetic_returns(1, 80, drift=0.004, scale=0.006)
    high_vol = _synthetic_returns(2, 80, drift=0.004, scale=0.02)
    sleeve_returns = {"low_vol": low_vol, "high_vol": high_vol}
    turnovers = {"low_vol": 0.0, "high_vol": 0.0}

    uncapped = allocate_quality_gated(sleeve_returns, turnovers, method="erc")
    assert sum(uncapped.values()) == pytest.approx(1.0, abs=1e-9)
    # ERC underweights the higher-variance sleeve relative to the lower-variance one.
    assert uncapped["low_vol"] > uncapped["high_vol"]

    capped = allocate_quality_gated(sleeve_returns, turnovers, method="erc", upper=0.6)
    assert sum(capped.values()) == pytest.approx(1.0, abs=1e-9)
    assert all(weight <= 0.6 + 1e-9 for weight in capped.values())
    assert capped["low_vol"] == pytest.approx(0.6, abs=1e-9)


def test_allocation_is_deterministic_across_two_runs() -> None:
    a = _synthetic_returns(1, 80, drift=0.004, scale=0.006)
    b = _synthetic_returns(2, 80, drift=0.004, scale=0.02)
    sleeve_returns = {"a": a, "b": b}
    turnovers = {"a": 0.0, "b": 0.0}

    first = allocate_quality_gated(sleeve_returns, turnovers, method="erc")
    second = allocate_quality_gated(sleeve_returns, turnovers, method="erc")

    assert first == second


def test_min_sleeves_gate_returns_empty_allocation_when_unmet() -> None:
    winning = _synthetic_returns(222, 64, drift=0.003, scale=0.01)

    weights = allocate_quality_gated({"winning": winning}, {"winning": 0.0}, min_sleeves=2)

    assert weights == {}


@pytest.mark.parametrize(
    "sleeve_returns,turnovers",
    [
        (None, None),
        ({}, {}),
        ({"x": None}, {"x": 0.01}),
        ({"x": []}, {"x": 0.01}),
    ],
)
def test_allocate_quality_gated_handles_none_and_empty_gracefully(
    sleeve_returns: Any, turnovers: Any
) -> None:
    assert allocate_quality_gated(sleeve_returns, turnovers) == {}


# ---------------------------------------------------------------------------
# (d) Byte-golden manifest serialization.
# ---------------------------------------------------------------------------

_GOLDEN_MANIFEST_SHA256 = "b50db777149a7c4a5c3bba53f698ac330a8ce1998ab20674f04f69a59d2739b9"


def test_manifest_serialization_matches_pinned_byte_golden() -> None:
    sleeves = {
        "alpha": {
            "returns": _synthetic_returns(12345, 64, drift=0.0025, scale=0.01),
            "turnover": 0.01,
            "strategy_class": "MovingAverageCrossStrategy",
            "symbols": ["BTC/USDT"],
            "params": {"short_window": 4, "long_window": 12},
            "source_artifact_id": "golden_source",
        },
        "beta": {
            "returns": _synthetic_returns(67890, 64, drift=0.0018, scale=0.02),
            "turnover": 0.02,
            "strategy_class": "MovingAverageCrossStrategy",
            "symbols": ["ETH/USDT"],
            "params": {"short_window": 6, "long_window": 20},
            "source_artifact_id": "golden_source",
        },
    }
    source_artifacts = [
        {
            "id": "golden_source",
            "path": "var/reports/golden/source.json",
            "sha256": "a" * 64,
            "max_age_hours": 100_000,
            "ready": True,
            "portfolio_ready": True,
        }
    ]

    manifest = build_allocation_manifest(
        sleeves, source_artifacts=source_artifacts, method="erc", gross_cap=1.0
    )
    serialized = json.dumps(manifest, sort_keys=True)

    assert all(
        child["lagged_completed_shadow_optimizer_provenance"] is False
        for child in manifest["children"]
    )
    assert hashlib.sha256(serialized.encode("utf-8")).hexdigest() == _GOLDEN_MANIFEST_SHA256
