import os
import random
from abc import ABC, abstractmethod
from copy import deepcopy
from typing import Any

from lumina_quant.backtesting.execution_model import (
    ExecutionModel,
    ExecutionModelConfig,
    _config_from_attrs,
)
from lumina_quant.core.events import FillEvent


def _env_flag(name: str, default: bool = False) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return bool(default)
    return str(raw).strip().lower() in {"1", "true", "yes", "on"}


class ExecutionHandler(ABC):
    """The ExecutionHandler abstract class handles the interaction
    between a set of order objects generated by a Portfolio and
    the ultimate set of Fill objects that actually occur in the
    market.
    """

    @abstractmethod
    def execute_order(self, event: Any) -> None:
        """Takes an Order event and executes it, producing
        a Fill event that gets placed onto the Events queue.
        """
        raise NotImplementedError


class SimulatedExecutionHandler(ExecutionHandler):
    """The simulated execution handler simply converts all order
    objects into their equivalent fill objects automatically
    without latency, slippage or fill-ratio issues.

    It allows a "Trailing Stop" which is simulated by tracking data updates.
    LMT orders are supported with strict-cross fill rules (see ExecutionModel docstring).
    """

    def __init__(self, events: Any, bars: Any, config: Any):
        self.events = events
        self.bars = bars
        self.config = config
        self.rng = random.Random(getattr(config, "RANDOM_SEED", 42))
        self._order_seq = 0

        # Phase 4 unified cost model — replaces FillModel + LiquidityModel for fills.
        # BacktestConfigView carries ._rt (RuntimeConfig); production path uses from_runtime.
        # Plain mock configs (unit tests) fall back to _config_from_attrs.
        _rt = getattr(config, "_rt", None)
        self.execution_model = ExecutionModel(
            ExecutionModelConfig.from_runtime(_rt)
            if _rt is not None
            else _config_from_attrs(config)
        )
        self.latency_model = LatencyModel(config)

        # Store conditional orders: { order_id: { 'symbol':..., 'type':..., 'trigger_price':..., 'parent_id':...} }
        # For simplicity, just list of order dicts
        self.active_orders: list[dict[str, Any]] = []

    def get_state(self) -> dict[str, Any]:
        state = {
            "active_orders": deepcopy(self.active_orders),
            "order_seq": int(self._order_seq),
            "rng_state": self.rng.getstate(),
            # Phase 4: execution_model._rng drives all fill randomness — must be
            # checkpointed so chunked runs produce the same sequence as a full run.
            "execution_model_rng_state": self.execution_model._rng.getstate(),
        }
        latency_get_state = getattr(self.latency_model, "get_state", None)
        if callable(latency_get_state):
            state["latency_model"] = latency_get_state()
        return state

    def set_state(self, state: dict[str, Any] | None) -> None:
        if not isinstance(state, dict):
            return
        active_orders = state.get("active_orders")
        if isinstance(active_orders, list):
            self.active_orders = deepcopy(active_orders)
        if "order_seq" in state:
            try:
                self._order_seq = int(state.get("order_seq", 0))
            except Exception:
                pass
        rng_state = state.get("rng_state")
        if rng_state is not None:
            try:
                self.rng.setstate(rng_state)
            except Exception:
                pass
        # Restore execution_model rng; gracefully skip if absent (old state dicts).
        em_rng_state = state.get("execution_model_rng_state")
        if em_rng_state is not None:
            try:
                self.execution_model._rng.setstate(em_rng_state)
            except Exception:
                pass
        latency_state = state.get("latency_model")
        latency_set_state = getattr(self.latency_model, "set_state", None)
        if isinstance(latency_state, dict) and callable(latency_set_state):
            latency_set_state(latency_state)

    def _next_order_id(self) -> str:
        self._order_seq += 1
        return f"SIM-{self._order_seq}"

    def _apply_slippage_and_comm(
        self, price: float, quantity: float, direction: str, symbol: str
    ) -> tuple[float, float]:
        """Helper to apply physics (Slippage/Fees/Spread) to a raw price.

        Delegates to ExecutionModel.compute_fill with no liquidity cap.
        Kept for backward compat — internal code now calls compute_fill directly.
        """
        high = self.bars.get_latest_bar_value(symbol, "high")
        low = self.bars.get_latest_bar_value(symbol, "low")
        open_p = self.bars.get_latest_bar_value(symbol, "open")
        volatility = (high - low) / open_p if open_p > 0 else 0.0
        result = self.execution_model.compute_fill(
            raw_price=float(price),
            qty=float(quantity),
            direction=str(direction),
            bar_volume=0.0,  # apply_liquidity_cap=False, bar_volume ignored
            volatility=float(volatility),
            is_maker=False,
            apply_liquidity_cap=False,
        )
        return result.fill_price, result.commission

    def _cancel_protective_orders(self, symbol: str, position_side: str | None = None) -> None:
        protected_types = {"STOP", "TAKE_PROFIT"}
        target_side = str(position_side).upper() if position_side else None
        kept: list[dict[str, Any]] = []
        for order in self.active_orders:
            if order.get("symbol") != symbol:
                kept.append(order)
                continue
            if str(order.get("type")) not in protected_types:
                kept.append(order)
                continue
            if not bool(order.get("is_protective", False)):
                kept.append(order)
                continue
            if target_side and str(order.get("position_side") or "").upper() not in {
                target_side,
                "",
            }:
                kept.append(order)
                continue
        self.active_orders = kept

    def _build_protective_orders(
        self,
        order: dict[str, Any],
        *,
        fill_price: float | None = None,
    ) -> list[dict[str, Any]]:
        if bool(order.get("reduce_only", False)):
            return []

        stop_loss = order.get("stop_loss")
        take_profit = order.get("take_profit")
        trailing_percent = order.get("trailing_percent")
        if (
            stop_loss is None
            and take_profit is None
            and (trailing_percent is None or float(trailing_percent) <= 0.0)
        ):
            return []

        position_side = order.get("position_side")
        if not position_side:
            position_side = "LONG" if order.get("direction") == "BUY" else "SHORT"

        exit_direction = "SELL" if order.get("direction") == "BUY" else "BUY"
        oco_group = f"{order.get('order_id')}-BRACKET"
        quantity = float(order.get("quantity") or 0.0)
        if quantity <= 0.0:
            return []

        out: list[dict[str, Any]] = []
        if stop_loss is not None:
            out.append(
                {
                    "order_id": self._next_order_id(),
                    "symbol": order.get("symbol"),
                    "type": "STOP",
                    "quantity": quantity,
                    "direction": exit_direction,
                    "stop_price": float(stop_loss),
                    "position_side": position_side,
                    "reduce_only": True,
                    "client_order_id": f"{order.get('client_order_id')}-SL"
                    if order.get("client_order_id")
                    else None,
                    "is_protective": True,
                    "oco_group": oco_group,
                    "parent_order_id": order.get("order_id"),
                }
            )

        if take_profit is not None:
            out.append(
                {
                    "order_id": self._next_order_id(),
                    "symbol": order.get("symbol"),
                    "type": "TAKE_PROFIT",
                    "quantity": quantity,
                    "direction": exit_direction,
                    "stop_price": float(take_profit),
                    "position_side": position_side,
                    "reduce_only": True,
                    "client_order_id": f"{order.get('client_order_id')}-TP"
                    if order.get("client_order_id")
                    else None,
                    "is_protective": True,
                    "oco_group": oco_group,
                    "parent_order_id": order.get("order_id"),
                }
            )

        if trailing_percent is not None and float(trailing_percent) > 0.0:
            trailing_value = float(trailing_percent)
            initial_price = float(fill_price) if fill_price is not None else None
            trailing_order = {
                "order_id": self._next_order_id(),
                "symbol": order.get("symbol"),
                "type": "TRAIL_STOP",
                "quantity": quantity,
                "direction": exit_direction,
                "position_side": position_side,
                "reduce_only": True,
                "client_order_id": f"{order.get('client_order_id')}-TRAIL"
                if order.get("client_order_id")
                else None,
                "is_protective": True,
                "oco_group": oco_group,
                "parent_order_id": order.get("order_id"),
                "trailing_percent": trailing_value,
                "stop_price": None,
                "highest_price": None,
                "lowest_price": None,
            }
            if exit_direction == "SELL" and initial_price is not None:
                trailing_order["highest_price"] = initial_price
                trailing_order["stop_price"] = initial_price * (1.0 - trailing_value)
            elif exit_direction == "BUY" and initial_price is not None:
                trailing_order["lowest_price"] = initial_price
                trailing_order["stop_price"] = initial_price * (1.0 + trailing_value)
            out.append(trailing_order)

        return out

    def execute_order(self, event: Any) -> None:
        """Receives OrderEvent.
        - MKT: Queues for Next Open execution (realism).
        - LMT: Queues for strict-cross fill on next bar.
        - STOP/TRAIL: triggers active monitoring.
        """
        if event.type == "ORDER":
            order_id = self._next_order_id()

            if event.order_type == "MKT":
                if bool(getattr(event, "reduce_only", False)):
                    self._cancel_protective_orders(
                        event.symbol,
                        getattr(event, "position_side", None),
                    )
                # LATENCY SIMULATION:
                # Do NOT fill immediately. Queue for Next Open.
                self.active_orders.append(
                    {
                        "order_id": order_id,
                        "symbol": event.symbol,
                        "type": "MKT",
                        "quantity": event.quantity,
                        "direction": event.direction,
                        "status": "PENDING",
                        "position_side": event.position_side,
                        "reduce_only": event.reduce_only,
                        "client_order_id": event.client_order_id,
                        "stop_loss": event.stop_loss,
                        "take_profit": event.take_profit,
                        "trailing_percent": event.trailing_percent,
                    }
                )

            elif event.order_type == "LMT":
                # LMT order: fills when bar strictly crosses limit_price.
                # BUY fills when bar_low  < limit_price (strict — not ≤).
                # SELL fills when bar_high > limit_price (strict — not ≥).
                limit_price = getattr(event, "price", None)
                if bool(getattr(event, "reduce_only", False)):
                    self._cancel_protective_orders(
                        event.symbol,
                        getattr(event, "position_side", None),
                    )
                self.active_orders.append(
                    {
                        "order_id": order_id,
                        "symbol": event.symbol,
                        "type": "LMT",
                        "quantity": event.quantity,
                        "direction": event.direction,
                        "limit_price": float(limit_price) if limit_price is not None else None,
                        "status": "PENDING",
                        "position_side": event.position_side,
                        "reduce_only": event.reduce_only,
                        "client_order_id": event.client_order_id,
                        "stop_loss": event.stop_loss,
                        "take_profit": event.take_profit,
                        "trailing_percent": event.trailing_percent,
                    }
                )

            elif event.order_type == "STOP":
                # Add to active orders
                self.active_orders.append(
                    {
                        "order_id": order_id,
                        "symbol": event.symbol,
                        "type": "STOP",
                        "quantity": event.quantity,
                        "direction": event.direction,
                        "stop_price": event.stop_price,
                        "position_side": event.position_side,
                        "reduce_only": event.reduce_only,
                        "client_order_id": event.client_order_id,
                    }
                )

            elif event.order_type == "TRAIL_STOP":
                # Add to active orders
                curr_price = self.bars.get_latest_bar_value(event.symbol, "close")
                # Initial stop price (if sent, else calculate)
                stop_price = event.stop_price

                self.active_orders.append(
                    {
                        "order_id": order_id,
                        "symbol": event.symbol,
                        "type": "TRAIL_STOP",
                        "quantity": event.quantity,
                        "direction": event.direction,
                        "stop_price": stop_price,
                        "trailing_percent": event.trailing_percent,
                        "highest_price": curr_price
                        if event.direction == "SELL"
                        else None,  # For Long Exit Trailing Stop
                        "lowest_price": curr_price
                        if event.direction == "BUY"
                        else None,  # For Short Exit Trailing Stop
                        "position_side": event.position_side,
                        "reduce_only": event.reduce_only,
                        "client_order_id": event.client_order_id,
                    }
                )

    def check_open_orders(self, event: Any) -> None:
        """Check active orders against the new MarketEvent.
        Handles MKT (Next Open), LMT (strict-cross), STOP/TP, TRAIL_STOP.
        """
        if event.type != "MARKET" or not self.active_orders:
            return

        bar_open = event.open
        bar_high = event.high
        bar_low = event.low
        bar_volume = event.volume
        # Normalised bar range — used to scale slippage on volatile bars.
        volatility = (bar_high - bar_low) / bar_open if bar_open > 0 else 0.0

        next_active_orders: list[dict[str, Any]] = []
        remainder_orders: list[dict[str, Any]] = []
        closed_oco_groups: set[str] = set()
        closed_positions: set[tuple[str, str | None]] = set()

        for order in self.active_orders:
            oco_group = order.get("oco_group")
            if oco_group and str(oco_group) in closed_oco_groups:
                continue

            if order["symbol"] != event.symbol:
                next_active_orders.append(order)
                continue

            triggered = False
            exec_price = None
            # Pre-computed fill result for MKT and LMT (computed inside their branches
            # so we don't double-consume the rng in the unified triggered block).
            _fill_result = None

            # ── MKT ORDER (Next Open) ─────────────────────────────────────────
            if order["type"] == "MKT" and order["status"] == "PENDING":
                if not self.latency_model.should_release(order):
                    next_active_orders.append(order)
                    continue
                exec_price = bar_open
                triggered = True

                original_qty = order["quantity"]
                _fill_result = self.execution_model.compute_fill(
                    raw_price=float(exec_price),
                    qty=float(original_qty),
                    direction=str(order["direction"]),
                    bar_volume=float(bar_volume),
                    volatility=float(volatility),
                    is_maker=False,
                    apply_liquidity_cap=True,
                )

                if _fill_result.unfilled_qty > 0.0:
                    if not _env_flag("LQ_BACKTEST_SUPPRESS_PARTIAL_FILL_LOGS", False):
                        print(
                            f"[Realism] Partial Fill: Req {original_qty} > Limit "
                            f"{_fill_result.executed_qty:.4f}. Filling "
                            f"{_fill_result.executed_qty} and keeping remainder."
                        )
                    remainder_orders.append(
                        {
                            "order_id": f"{order['order_id']}-R",
                            "symbol": order["symbol"],
                            "type": "MKT",
                            "quantity": _fill_result.unfilled_qty,
                            "direction": order["direction"],
                            "status": "PENDING",
                            "position_side": order.get("position_side"),
                            "reduce_only": order.get("reduce_only", False),
                            "client_order_id": order.get("client_order_id"),
                            "stop_loss": order.get("stop_loss"),
                            "take_profit": order.get("take_profit"),
                            "trailing_percent": order.get("trailing_percent"),
                        }
                    )
                order["quantity"] = _fill_result.executed_qty

            # ── LMT ORDER (strict-cross fill) ─────────────────────────────────
            elif order["type"] == "LMT" and order.get("status") == "PENDING":
                limit_price = order.get("limit_price")
                if limit_price is None or float(limit_price) <= 0.0:
                    next_active_orders.append(order)
                    continue
                limit_price = float(limit_price)
                direction = str(order["direction"]).upper()
                # Strict cross: BUY fills when bar_low < limit (not ≤).
                #               SELL fills when bar_high > limit (not ≥).
                if (direction == "BUY" and bar_low < limit_price) or (
                    direction == "SELL" and bar_high > limit_price
                ):
                    exec_price = limit_price
                    triggered = True

                if triggered:
                    original_qty = order["quantity"]
                    _fill_result = self.execution_model.compute_fill(
                        raw_price=float(exec_price),
                        qty=float(original_qty),
                        direction=str(order["direction"]),
                        bar_volume=float(bar_volume),
                        volatility=0.0,  # LMT fills at exact price — no slippage
                        is_maker=True,
                        apply_liquidity_cap=True,
                    )
                    if _fill_result.unfilled_qty > 0.0:
                        remainder_orders.append(
                            {
                                "order_id": f"{order['order_id']}-R",
                                "symbol": order["symbol"],
                                "type": "LMT",
                                "quantity": _fill_result.unfilled_qty,
                                "direction": order["direction"],
                                "limit_price": limit_price,
                                "status": "PENDING",
                                "position_side": order.get("position_side"),
                                "reduce_only": order.get("reduce_only", False),
                                "client_order_id": order.get("client_order_id"),
                                "stop_loss": order.get("stop_loss"),
                                "take_profit": order.get("take_profit"),
                                "trailing_percent": order.get("trailing_percent"),
                            }
                        )
                    order["quantity"] = _fill_result.executed_qty

            # ── STOP ORDER ────────────────────────────────────────────────────
            elif order["type"] == "STOP":
                if order["direction"] == "SELL" and bar_low <= order["stop_price"]:
                    exec_price = order["stop_price"]
                    if exec_price > bar_open:
                        exec_price = bar_open
                    triggered = True
                elif order["direction"] == "BUY" and bar_high >= order["stop_price"]:
                    exec_price = order["stop_price"]
                    if exec_price < bar_open:
                        exec_price = bar_open
                    triggered = True

            # ── TAKE PROFIT ORDER ─────────────────────────────────────────────
            elif order["type"] == "TAKE_PROFIT":
                target = float(order["stop_price"])
                if order["direction"] == "SELL" and bar_high >= target:
                    exec_price = target
                    if bar_open > exec_price:
                        exec_price = bar_open
                    triggered = True
                elif order["direction"] == "BUY" and bar_low <= target:
                    exec_price = target
                    if bar_open < exec_price:
                        exec_price = bar_open
                    triggered = True

            # ── TRAILING STOP ─────────────────────────────────────────────────
            elif order["type"] == "TRAIL_STOP":
                if order["direction"] == "SELL":
                    if order["highest_price"] is None or bar_high > order["highest_price"]:
                        order["highest_price"] = bar_high
                        order["stop_price"] = order["highest_price"] * (
                            1.0 - order["trailing_percent"]
                        )

                    if bar_low <= order["stop_price"]:
                        exec_price = order["stop_price"]
                        if bar_open < exec_price:
                            exec_price = bar_open
                        triggered = True
                elif order["direction"] == "BUY":
                    if order["lowest_price"] is None or bar_low < order["lowest_price"]:
                        order["lowest_price"] = bar_low
                        order["stop_price"] = order["lowest_price"] * (
                            1.0 + order["trailing_percent"]
                        )

                    if bar_high >= order["stop_price"]:
                        exec_price = order["stop_price"]
                        if bar_open > exec_price:
                            exec_price = bar_open
                        triggered = True

            # ── Unified fill emission ──────────────────────────────────────────
            if triggered and exec_price is not None:
                if _fill_result is not None:
                    # MKT or LMT — fill already computed in the branch above.
                    fill_price = _fill_result.fill_price
                    comm = _fill_result.commission
                else:
                    # STOP, TAKE_PROFIT, TRAIL_STOP — no liquidity cap; aggressive fill.
                    cond_result = self.execution_model.compute_fill(
                        raw_price=float(exec_price),
                        qty=float(order["quantity"]),
                        direction=str(order["direction"]),
                        bar_volume=float(bar_volume),
                        volatility=float(volatility),
                        is_maker=False,
                        apply_liquidity_cap=False,
                    )
                    fill_price = cond_result.fill_price
                    comm = cond_result.commission

                fill_event = FillEvent(
                    timeindex=event.time,
                    symbol=order["symbol"],
                    exchange="BINANCE_SIM",
                    quantity=order["quantity"],
                    direction=order["direction"],
                    fill_cost=fill_price * order["quantity"],
                    commission=comm,
                    order_id=order.get("order_id"),
                    client_order_id=order.get("client_order_id"),
                    position_side=order.get("position_side"),
                    status="FILLED",
                    metadata={
                        "reduce_only": order.get("reduce_only", False),
                        "signal_metadata": dict(order.get("metadata") or {}),
                        "component_id": str(
                            dict(order.get("metadata") or {}).get("component_id") or ""
                        ).strip()
                        or None,
                    },
                )
                self.events.put(fill_event)

                if order.get("type") in {"MKT", "LMT"}:
                    remainder_orders.extend(
                        self._build_protective_orders(order, fill_price=fill_price)
                    )

                if bool(order.get("reduce_only", False)):
                    closed_positions.add(
                        (
                            str(order.get("symbol")),
                            str(order.get("position_side")).upper()
                            if order.get("position_side")
                            else None,
                        )
                    )

                if oco_group:
                    closed_oco_groups.add(str(oco_group))
                continue

            if oco_group and str(oco_group) in closed_oco_groups:
                continue
            next_active_orders.append(order)

        if closed_positions:
            filtered: list[dict[str, Any]] = []
            for order in next_active_orders:
                if str(order.get("type")) not in {"STOP", "TAKE_PROFIT"}:
                    filtered.append(order)
                    continue
                if not bool(order.get("is_protective", False)):
                    filtered.append(order)
                    continue
                symbol = str(order.get("symbol"))
                side = (
                    str(order.get("position_side")).upper() if order.get("position_side") else None
                )
                matched = False
                for c_symbol, c_side in closed_positions:
                    if symbol != c_symbol:
                        continue
                    if c_side is None or side is None or side == c_side:
                        matched = True
                        break
                if not matched:
                    filtered.append(order)
            next_active_orders = filtered

        if remainder_orders:
            next_active_orders.extend(remainder_orders)
        self.active_orders = next_active_orders


class LatencyModel:
    """Simple latency model releasing queued orders on next check cycle."""

    def __init__(self, config: Any):
        seed = int(getattr(config, "RANDOM_SEED", 42))
        self.rng = random.Random(seed + 701)
        self.min_bars = max(1, int(getattr(config, "SIM_LATENCY_MIN_BARS", 1)))
        self.max_bars = max(self.min_bars, int(getattr(config, "SIM_LATENCY_MAX_BARS", 1)))

    def get_state(self) -> dict[str, Any]:
        return {"rng_state": self.rng.getstate()}

    def set_state(self, state: dict[str, Any] | None) -> None:
        if not isinstance(state, dict):
            return
        rng_state = state.get("rng_state")
        if rng_state is None:
            return
        try:
            self.rng.setstate(rng_state)
        except Exception:
            pass

    def should_release(self, order: dict[str, Any]) -> bool:
        target = order.get("_latency_target_bars")
        if target is None:
            target = int(self.rng.randint(int(self.min_bars), int(self.max_bars)))
            order["_latency_target_bars"] = int(target)
        waited = int(order.get("_latency_waited_bars", 0)) + 1
        order["_latency_waited_bars"] = int(waited)
        return int(waited) >= int(target)


__all__ = [
    "ExecutionHandler",
    "LatencyModel",
    "SimulatedExecutionHandler",
]
