#!/usr/bin/env python3
"""Build the Alpha Zoo 10bps full-retune gate artifact.

The runner is intentionally conservative: promotion is evaluated only at the
primary 10bps round-trip cost baseline, all locked-OOS usage is report/gate-only,
and historical OOS/top-bucket seed-union candidates remain shadow references
unless regenerated by a train+validation-only retune path.
"""

from __future__ import annotations

import argparse
import csv
import heapq
import json
import math
import resource
import sys
from collections.abc import Mapping, Sequence
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.research import run_alpha_zoo_top_seed_hybrid_v35_v36_cost_validation as cost  # noqa: E402
from scripts.research import run_alpha_zoo_validation_march_high_leverage as high  # noqa: E402

DEFAULT_OUTPUT_DIR = (
    high.DEFAULT_ALPHA_V2 / "alpha_zoo_10bps_full_retune_20260519"
)
DEFAULT_SOURCE_COST_DIR = high.DEFAULT_ALPHA_V2 / "alpha_zoo_top_seed_hybrid_cost_validation_20260518"
DEFAULT_SOURCE_COST_JSON = (
    DEFAULT_SOURCE_COST_DIR / "alpha_zoo_top_seed_hybrid_cost_validation_latest.json"
)
DEFAULT_SOURCE_COST_METRICS_CSV = DEFAULT_SOURCE_COST_DIR / "model_cost_metrics_latest.csv"
DEFAULT_SOURCE_LIVE_JSON = high.DEFAULT_ALPHA_V2 / (
    "live_notional_risk_aligned_alpha_zoo_20260518/"
    "alpha_zoo_validation_march_high_leverage_latest.json"
)
DEFAULT_SOURCE_CANDIDATE_CSV = high.DEFAULT_ALPHA_V2 / (
    "live_notional_risk_aligned_alpha_zoo_20260518/"
    "alpha_zoo_validation_march_high_leverage_candidates_latest.csv"
)
EXPECTED_TIMESTAMP_INDEX_HASH = "b973165bc1057f3aaa08ea637b73a45df3e84fdb7d1337b1637233d205696bb0"
PRIMARY_COST_BPS = 10.0
MEMORY_LIMIT_MIB = 8192.0
SPLIT_ORDER = ("train", "validation", "locked_oos")
TV_SPLITS = ("train", "validation")
PROMOTION_METRIC_KEYS = ("total_return", "sharpe", "sortino", "smart_sortino", "calmar")
POSITIVE_PROMOTION_METRIC_KEYS = ("sharpe", "sortino", "smart_sortino", "calmar")
CALENDAR_PARAM_KEYS = {
    "calendar_long_months",
    "calendar_short_months",
    "calendar_months",
    "entry_days_of_month",
    "entry_hours",
    "entry_months",
    "month_filter",
    "day_filter",
    "hour_filter",
    "date_filter",
}
EXECUTION_COST_SYMBOLS = ("BTCUSDT", "ETHUSDT", "SOLUSDT", "BNBUSDT", "TRXUSDT")


def _utc_now_iso() -> str:
    return datetime.now(UTC).isoformat().replace("+00:00", "Z")


def _rss_mib() -> float:
    peak = int(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss or 0)
    if sys.platform == "darwin":
        return peak / (1024.0 * 1024.0)
    return peak / 1024.0


def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        parsed = float(value)
    except (TypeError, ValueError, OverflowError):
        return default
    return parsed if math.isfinite(parsed) else default


def _safe_int(value: Any, default: int = 0) -> int:
    try:
        return int(float(value))
    except (TypeError, ValueError, OverflowError):
        return default


def _as_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"1", "true", "yes", "y"}


def _json_safe(value: Any) -> Any:
    if isinstance(value, np.generic):
        return value.item()
    if isinstance(value, float):
        return value if math.isfinite(value) else None
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, (datetime,)):
        return value.isoformat()
    if isinstance(value, Mapping):
        return {str(key): _json_safe(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_safe(item) for item in value]
    return value


def _write_json(path: Path, payload: Mapping[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(_json_safe(payload), ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def _write_csv(path: Path, rows: Sequence[Mapping[str, Any]], fieldnames: Sequence[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(
            fh,
            fieldnames=list(fieldnames),
            extrasaction="ignore",
            lineterminator="\n",
        )
        writer.writeheader()
        for row in rows:
            writer.writerow({key: _csv_value(row.get(key)) for key in fieldnames})


def _csv_value(value: Any) -> Any:
    if isinstance(value, (list, tuple)):
        return ";".join(str(item) for item in value)
    if isinstance(value, Mapping):
        return json.dumps(_json_safe(value), sort_keys=True)
    return _json_safe(value)


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _read_csv(path: Path) -> list[dict[str, Any]]:
    with path.open(newline="", encoding="utf-8") as fh:
        return [dict(row) for row in csv.DictReader(fh)]


def _cost_adjusted_trade_return(
    alpha: Any,
    trade: Mapping[str, Any],
    *,
    leverage: float,
    allocation_fraction: float,
    round_trip_slippage_bps: float = PRIMARY_COST_BPS,
) -> tuple[float, bool]:
    """Return isolated account-level trade return after explicit round-trip bps cost."""
    return cost._cost_adjusted_trade_return(
        alpha,
        trade,
        leverage=float(leverage),
        allocation_fraction=float(allocation_fraction),
        round_trip_slippage_bps=float(round_trip_slippage_bps),
    )


def _train_validation_score(split_metrics: Mapping[str, Mapping[str, Any]]) -> float:
    """Score only train+validation metrics; locked-OOS is intentionally unread."""
    train = dict(split_metrics.get("train") or {})
    validation = dict(split_metrics.get("validation") or {})
    val_return = _safe_float(validation.get("total_return"))
    train_return = _safe_float(train.get("total_return"))
    val_mdd = _safe_float(validation.get("max_drawdown"), 1.0)
    train_mdd = _safe_float(train.get("max_drawdown"), 1.0)
    score = (
        10.0 * val_return
        + 0.25 * train_return
        + 0.10 * _safe_float(validation.get("sharpe"))
        + 0.10 * _safe_float(validation.get("sortino"))
        + 0.10 * _safe_float(validation.get("smart_sortino"))
        + 0.10 * _safe_float(validation.get("calmar"))
        - 3.0 * max(0.0, val_mdd - high.OOS_MDD_BUDGET)
        - 0.25 * max(0.0, train_mdd - high.OOS_MDD_BUDGET)
    )
    if val_return <= 0.0:
        score -= 100.0 + abs(val_return) * 10.0
    if train_return <= 0.0:
        score -= 50.0 + abs(train_return) * 5.0
    return float(score)


def _split_metrics_from_rows(rows: Sequence[Mapping[str, Any]]) -> dict[str, dict[str, Any]]:
    out: dict[str, dict[str, Any]] = {}
    for row in rows:
        split = str(row.get("split") or "")
        if split not in SPLIT_ORDER:
            continue
        out[split] = {
            "total_return": _safe_float(row.get("total_return")),
            "max_drawdown": _safe_float(row.get("max_drawdown")),
            "sharpe": _safe_float(row.get("sharpe")),
            "sortino": _safe_float(row.get("sortino")),
            "smart_sortino": _safe_float(row.get("smart_sortino")),
            "calmar": _safe_float(row.get("calmar")),
            "return_mdd": _safe_float(row.get("return_mdd")),
            "trade_count": _safe_int(row.get("trade_event_count")),
            "active_return_hours": _safe_int(row.get("active_return_hours")),
            "liquidation_count": _safe_int(row.get("liquidation_count")),
            "account_wipeout_count": _safe_int(row.get("account_wipeout_count")),
            "minimum_margin_buffer": (
                None
                if row.get("minimum_margin_buffer") in {"", None}
                else _safe_float(row.get("minimum_margin_buffer"), -1.0)
            ),
        }
    return out


def _split_metrics_from_prefixed_row(row: Mapping[str, Any]) -> dict[str, dict[str, Any]]:
    """Build split metrics from a flat row using ``train_*``/``validation_*`` keys."""
    out: dict[str, dict[str, Any]] = {}
    for split in SPLIT_ORDER:
        out[split] = {
            "total_return": _safe_float(row.get(f"{split}_total_return"), _safe_float(row.get(f"{split}_return"))),
            "max_drawdown": _safe_float(row.get(f"{split}_max_drawdown"), _safe_float(row.get(f"{split}_mdd"))),
            "sharpe": _safe_float(row.get(f"{split}_sharpe")),
            "sortino": _safe_float(row.get(f"{split}_sortino")),
            "smart_sortino": _safe_float(row.get(f"{split}_smart_sortino")),
            "calmar": _safe_float(row.get(f"{split}_calmar")),
            "return_mdd": _safe_float(row.get(f"{split}_return_mdd")),
            "trade_count": _safe_int(row.get(f"{split}_trade_count")),
            "active_return_hours": _safe_int(row.get(f"{split}_active_return_hours")),
            "liquidation_count": _safe_int(row.get(f"{split}_liquidation_count")),
            "account_wipeout_count": _safe_int(row.get(f"{split}_account_wipeout_count")),
            "minimum_margin_buffer": row.get(f"{split}_minimum_margin_buffer", row.get("minimum_margin_buffer")),
        }
    return out


def _promotion_gate_reasons(
    split_metrics: Mapping[str, Mapping[str, Any]],
    *,
    cost_bps: float,
    candidate_universe_uses_locked_oos_bucket: bool = False,
    regenerated_train_validation_only: bool = True,
    promotability_scope: str = "live_candidate",
    strict_zero_liquidation: bool = True,
) -> list[str]:
    reasons: list[str] = []
    if not math.isclose(float(cost_bps), PRIMARY_COST_BPS, abs_tol=1e-9):
        reasons.append("primary_cost_not_10bps")
    missing = [split for split in SPLIT_ORDER if split not in split_metrics]
    if missing:
        reasons.append("missing_split_metrics:" + ",".join(missing))

    if candidate_universe_uses_locked_oos_bucket:
        reasons.append("candidate_universe_uses_locked_oos_bucket")
    if promotability_scope == "shadow_only":
        reasons.append("shadow_only_historical_oos_bucket_lineage")

    train = dict(split_metrics.get("train") or {})
    validation = dict(split_metrics.get("validation") or {})
    locked_oos = dict(split_metrics.get("locked_oos") or {})
    for split_name, metrics in (("validation", validation), ("locked_oos", locked_oos)):
        if _safe_float(metrics.get("total_return")) <= 0.0:
            reasons.append(f"{split_name}_return_non_positive")
        for metric_key in POSITIVE_PROMOTION_METRIC_KEYS:
            if _safe_float(metrics.get(metric_key)) <= 0.0:
                reasons.append(f"{split_name}_{metric_key}_non_positive")

    if _safe_float(train.get("total_return")) <= 0.0:
        reasons.append("train_return_non_positive")
    for metric_key in PROMOTION_METRIC_KEYS:
        train_value = _safe_float(train.get(metric_key))
        validation_value = _safe_float(validation.get(metric_key))
        locked_value = _safe_float(locked_oos.get(metric_key))
        if train_value <= validation_value:
            reasons.append(f"train_{metric_key}_not_above_validation")
        if train_value <= locked_value:
            reasons.append(f"train_{metric_key}_not_above_locked_oos")

    if _safe_float(locked_oos.get("max_drawdown"), 1.0) > high.OOS_MDD_BUDGET:
        reasons.append("locked_oos_mdd_above_25pct")

    total_liquidations = 0
    for split in SPLIT_ORDER:
        metrics = dict(split_metrics.get(split) or {})
        if _safe_int(metrics.get("account_wipeout_count")) > 0:
            reasons.append(f"{split}_account_wipeout_count_positive")
        total_liquidations += _safe_int(metrics.get("liquidation_count"))
        if metrics.get("minimum_margin_buffer") is not None and _safe_float(
            metrics.get("minimum_margin_buffer"), -1.0
        ) <= 0.0:
            reasons.append(f"{split}_minimum_margin_buffer_non_positive")
    if strict_zero_liquidation and total_liquidations > 0:
        reasons.append("liquidation_count_positive")

    return sorted(set(reasons))


def _promotion_gate_result(
    split_metrics: Mapping[str, Mapping[str, Any]],
    *,
    cost_bps: float,
    candidate_universe_uses_locked_oos_bucket: bool = False,
    regenerated_train_validation_only: bool = True,
    promotability_scope: str = "live_candidate",
    strict_zero_liquidation: bool = True,
) -> dict[str, Any]:
    reasons = _promotion_gate_reasons(
        split_metrics,
        cost_bps=float(cost_bps),
        candidate_universe_uses_locked_oos_bucket=bool(candidate_universe_uses_locked_oos_bucket),
        regenerated_train_validation_only=bool(regenerated_train_validation_only),
        promotability_scope=str(promotability_scope),
        strict_zero_liquidation=bool(strict_zero_liquidation),
    )
    return {
        "round_trip_slippage_fee_bps": float(cost_bps),
        "live_promotable_10bps": not reasons,
        "primary_10bps_promotion_gate_pass": not reasons,
        "primary_10bps_promotion_gate_reasons": reasons,
        "candidate_universe_uses_locked_oos_bucket": bool(candidate_universe_uses_locked_oos_bucket),
        "regenerated_train_validation_only": bool(regenerated_train_validation_only),
        "promotability_scope": str(promotability_scope),
        "strict_zero_liquidation": bool(strict_zero_liquidation),
    }


def promotion_gate(row: Mapping[str, Any]) -> dict[str, Any]:
    """Compatibility wrapper for tests and ad-hoc gate probes over flat rows."""
    split_metrics = _split_metrics_from_prefixed_row(row)
    result = _promotion_gate_result(
        split_metrics,
        cost_bps=_safe_float(row.get("round_trip_slippage_fee_bps"), PRIMARY_COST_BPS),
        candidate_universe_uses_locked_oos_bucket=_as_bool(
            row.get("candidate_universe_uses_locked_oos_bucket")
        ),
        regenerated_train_validation_only=_as_bool(row.get("regenerated_train_validation_only")),
        promotability_scope="shadow_only"
        if _as_bool(row.get("shadow_only"))
        else str(row.get("promotability_scope") or "live_candidate"),
        strict_zero_liquidation=True,
    )
    raw_params = row.get("params", row.get("params_json", {}))
    if isinstance(raw_params, Mapping):
        params = dict(raw_params)
    elif isinstance(raw_params, str) and raw_params.strip():
        try:
            loaded_params = json.loads(raw_params)
        except json.JSONDecodeError:
            loaded_params = {}
        params = dict(loaded_params) if isinstance(loaded_params, Mapping) else {}
    else:
        params = {}
    reasons = list(result["primary_10bps_promotion_gate_reasons"])
    if _as_bool(row.get("calendar_primary")) or _variant_has_calendar_rule(params):
        reasons.append("calendar_or_date_rule_forbidden")
    compatibility_reason_names = {
        "train_total_return_not_above_validation": "train_return_not_above_validation",
        "train_total_return_not_above_locked_oos": "train_return_not_above_locked_oos",
    }
    reasons = [compatibility_reason_names.get(reason, reason) for reason in reasons]
    reasons = sorted(set(reasons))
    return {
        "promotion_gate_pass": not reasons,
        "promotion_gate_reasons": reasons,
    }


primary_promotion_gate = _promotion_gate_result
_primary_promotion_gate = _promotion_gate_result
_primary_promotion_gate_reasons = _promotion_gate_reasons


def _calendar_rule_reasons(params: Mapping[str, Any]) -> list[str]:
    reasons: list[str] = []
    for key, value in params.items():
        key_text = str(key)
        if isinstance(value, Mapping):
            nested = _calendar_rule_reasons(value)
            reasons.extend(f"{key_text}.{item}" for item in nested)
            continue
        is_calendar_key = key_text in CALENDAR_PARAM_KEYS
        if not is_calendar_key:
            continue
        if value not in (None, "", (), [], {}):
            reasons.append(key_text)
    return sorted(set(reasons))


def _variant_has_calendar_rule(params: Mapping[str, Any]) -> bool:
    return bool(_calendar_rule_reasons(params))


def _variant_row(
    *,
    candidate_name: str,
    variant_name: str,
    params: Mapping[str, Any],
    source: str,
) -> dict[str, Any]:
    reasons = _calendar_rule_reasons(params)
    return {
        "candidate_name": candidate_name,
        "variant_name": variant_name,
        "source": source,
        "calendar_primary": bool(reasons),
        "calendar_rule_rejection_reasons": reasons,
        "variant_gate_pass": not reasons,
        "params_json": json.dumps(_json_safe(dict(params)), sort_keys=True),
    }


def _scaled_param_variant(
    params: Mapping[str, Any],
    *,
    key: str,
    factor: float,
    suffix: str,
) -> tuple[str, dict[str, Any]] | None:
    if key not in params:
        return None
    value = _safe_float(params.get(key), math.nan)
    if not math.isfinite(value):
        return None
    out = dict(params)
    out[key] = value * factor
    return suffix, out


def _build_variant_inventory(source_live_payload: Mapping[str, Any]) -> list[dict[str, Any]]:
    selection = dict(source_live_payload.get("selection") or {})
    summaries = list(selection.get("strategy_summaries") or [])
    rows: list[dict[str, Any]] = []
    seen: set[tuple[str, str]] = set()
    for item in summaries:
        candidate_name = str(dict(item).get("candidate_name") or "")
        source = str(dict(item).get("candidate_source") or "source_live_aligned")
        params = dict(dict(item).get("params") or {})
        if not candidate_name:
            continue
        variants: list[tuple[str, dict[str, Any]]] = [("base", params)]
        for spec in (
            _scaled_param_variant(params, key="entry_threshold", factor=1.10, suffix="entry_10pct_stricter"),
            _scaled_param_variant(params, key="entry_threshold", factor=1.25, suffix="entry_25pct_stricter"),
            _scaled_param_variant(params, key="exit_threshold", factor=1.25, suffix="exit_hysteresis_25pct_wider"),
            _scaled_param_variant(params, key="max_hold_bars", factor=1.50, suffix="max_hold_50pct_longer"),
        ):
            if spec is not None:
                variants.append(spec)
        for variant_name, variant_params in variants:
            key = (candidate_name, variant_name)
            if key in seen:
                continue
            seen.add(key)
            rows.append(
                _variant_row(
                    candidate_name=candidate_name,
                    variant_name=variant_name,
                    params=variant_params,
                    source=source,
                )
            )
    return rows


def _load_source_metric_rows(
    source_payload: Mapping[str, Any],
    source_cost_metrics_csv: Path,
) -> list[dict[str, Any]]:
    rows = [dict(row) for row in list(source_payload.get("model_cost_metrics") or [])]
    if rows:
        return rows
    return _read_csv(source_cost_metrics_csv)


def _group_metric_rows_by_model(rows: Sequence[Mapping[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    grouped: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        if not math.isclose(_safe_float(row.get("round_trip_slippage_fee_bps")), PRIMARY_COST_BPS):
            continue
        model_id = str(row.get("model_id") or "")
        if not model_id:
            continue
        grouped.setdefault(model_id, []).append(dict(row))
    for model_id, model_rows in grouped.items():
        splits = {str(row.get("split")) for row in model_rows}
        missing = set(SPLIT_ORDER) - splits
        if missing:
            raise ValueError(f"{model_id} missing primary 10bps split rows: {sorted(missing)}")
    return grouped


def _model_identity(model_rows: Sequence[Mapping[str, Any]]) -> dict[str, Any]:
    first = dict(model_rows[0]) if model_rows else {}
    return {
        "model_id": str(first.get("model_id") or ""),
        "model_kind": str(first.get("model_kind") or ""),
        "role": str(first.get("role") or ""),
        "candidate_name": str(first.get("candidate_name") or ""),
        "leverage": first.get("leverage", ""),
        "allocation_fraction": first.get("allocation_fraction", ""),
    }


def _source_rows_are_shadow_only(source_payload: Mapping[str, Any]) -> bool:
    policy = dict(source_payload.get("selection_policy") or {})
    return _as_bool(policy.get("post_hoc_seed_basket_uses_leaderboard_oos_buckets_by_request"))


def _slug(value: Any) -> str:
    text = str(value or "").strip().lower()
    out = []
    for ch in text:
        if ch.isalnum():
            out.append(ch)
        elif ch == ".":
            out.append("p")
        else:
            out.append("_")
    return "_".join("".join(out).split("_")).strip("_") or "model"


def _candidate_key(row: Mapping[str, Any]) -> tuple[str, float, float]:
    return (
        str(row.get("candidate_name") or ""),
        _safe_float(row.get("leverage")),
        _safe_float(row.get("allocation_fraction")),
    )


def _fresh_model_id(prefix: str, row: Mapping[str, Any]) -> str:
    return (
        f"{prefix}_{_slug(row.get('candidate_name'))}_"
        f"{_slug(_safe_float(row.get('leverage')))}x_"
        f"{_slug(_safe_float(row.get('allocation_fraction')))}alloc"
    )


def _candidate_rows_for_fresh_retune(
    source_candidate_rows: Sequence[Mapping[str, Any]],
    *,
    limit: int,
) -> list[dict[str, Any]]:
    """Return TV-frozen candidate rows to recompute at the primary 10bps cost."""
    if int(limit) <= 0:
        return []
    deduped: dict[tuple[str, float, float], dict[str, Any]] = {}
    for raw in source_candidate_rows:
        row = dict(raw)
        key = _candidate_key(row)
        if not key[0]:
            continue
        if key not in deduped:
            deduped[key] = row

    def sort_key(row: Mapping[str, Any]) -> tuple[int, float, str]:
        rank = _safe_int(row.get("frozen_train_validation_rank"), 10**9)
        score = _safe_float(row.get("tv_selection_score"), -1e9)
        return (rank, -score, str(row.get("candidate_name") or ""))

    return sorted(deduped.values(), key=sort_key)[: int(limit)]


def _summary_from_split_metrics(
    *,
    model_id: str,
    model_kind: str,
    role: str,
    split_metrics: Mapping[str, Mapping[str, Any]],
    score: float,
    gate: Mapping[str, Any],
    candidate_name: str = "",
    leverage: float | None = None,
    allocation_fraction: float | None = None,
    extra_fields: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    return {
        "model_id": model_id,
        "model_kind": model_kind,
        "role": role,
        "candidate_name": candidate_name,
        "leverage": "" if leverage is None else float(leverage),
        "allocation_fraction": "" if allocation_fraction is None else float(allocation_fraction),
        "round_trip_slippage_fee_bps": PRIMARY_COST_BPS,
        "train_validation_score": float(score),
        "candidate_universe_uses_locked_oos_bucket": gate[
            "candidate_universe_uses_locked_oos_bucket"
        ],
        "regenerated_train_validation_only": gate["regenerated_train_validation_only"],
        "promotability_scope": gate["promotability_scope"],
        "shadow_only": gate["promotability_scope"] == "shadow_only",
        "primary_10bps_promotion_gate_pass": gate["primary_10bps_promotion_gate_pass"],
        "primary_10bps_promotion_gate_reasons": gate[
            "primary_10bps_promotion_gate_reasons"
        ],
        "live_promotable_10bps": gate["live_promotable_10bps"],
        "train": dict(split_metrics.get("train") or {}),
        "validation": dict(split_metrics.get("validation") or {}),
        "locked_oos": dict(split_metrics.get("locked_oos") or {}),
        **dict(extra_fields or {}),
    }


def _metric_rows_from_split_metrics(
    *,
    model_id: str,
    model_kind: str,
    role: str,
    split_metrics: Mapping[str, Mapping[str, Any]],
    score: float,
    gate: Mapping[str, Any],
    candidate_name: str = "",
    leverage: float | None = None,
    allocation_fraction: float | None = None,
    strict_zero_liquidation: bool = True,
    extra_fields: Mapping[str, Any] | None = None,
) -> list[dict[str, Any]]:
    rows = cost._metric_rows_for_model(
        model_id=model_id,
        model_kind=model_kind,
        role=role,
        cost_bps=PRIMARY_COST_BPS,
        split_metrics=split_metrics,
        candidate_name=candidate_name,
        leverage=leverage,
        allocation_fraction=allocation_fraction,
        strict_zero_liquidation=bool(strict_zero_liquidation),
    )
    for row in rows:
        row.update(
            {
                "train_validation_score": float(score),
                "candidate_universe_uses_locked_oos_bucket": gate[
                    "candidate_universe_uses_locked_oos_bucket"
                ],
                "regenerated_train_validation_only": gate[
                    "regenerated_train_validation_only"
                ],
                "promotability_scope": gate["promotability_scope"],
                "shadow_only": gate["promotability_scope"] == "shadow_only",
                "calendar_primary": False,
                "primary_10bps_promotion_gate_pass": gate[
                    "primary_10bps_promotion_gate_pass"
                ],
                "primary_10bps_promotion_gate_reasons": ";".join(
                    gate["primary_10bps_promotion_gate_reasons"]
                ),
                "live_promotable_10bps": gate["live_promotable_10bps"],
                **dict(extra_fields or {}),
            }
        )
    return rows


def _trade_entry_metadata(trade: Mapping[str, Any]) -> Mapping[str, Any]:
    metadata = trade.get("entry_metadata")
    return metadata if isinstance(metadata, Mapping) else {}


def _trade_factor_family(trade: Mapping[str, Any]) -> str:
    return str(_trade_entry_metadata(trade).get("dominant_factor_family") or "")


def _trade_abs_factor_score(trade: Mapping[str, Any]) -> float:
    return abs(_safe_float(_trade_entry_metadata(trade).get("factor_score")))


def _trade_hold_hours(trade: Mapping[str, Any]) -> float:
    try:
        return max(
            0.0,
            (
                cost._timestamp_seconds(trade.get("exit_time"))
                - cost._timestamp_seconds(trade.get("entry_time"))
            )
            / 3600.0,
        )
    except (TypeError, ValueError, OverflowError):
        return 0.0


def _trade_filter_variant_specs(
    trades: Sequence[Mapping[str, Any]],
) -> list[tuple[str, dict[str, Any], Any]]:
    """Return a fixed non-calendar trade-filter grid.

    The grid is intentionally expressed in trade metadata dimensions that are
    strategy-theoretic (side, symbol, factor family, factor-score strength, and
    holding-time cap).  It never uses calendar/date fields and is ranked only on
    train+validation metrics before locked-OOS gates are attached.
    """
    symbols = sorted({str(trade.get("symbol") or "") for trade in trades if trade.get("symbol")})
    families = sorted({_trade_factor_family(trade) for trade in trades if _trade_factor_family(trade)})
    specs: list[tuple[str, dict[str, Any], Any]] = []
    for side in ("LONG", "SHORT"):
        specs.append(
            (
                f"side_{side.lower()}",
                {"side": side},
                lambda trade, side=side: str(trade.get("side") or "") == side,
            )
        )
    for symbol in symbols:
        specs.append(
            (
                f"symbol_{_slug(symbol)}",
                {"symbol": symbol},
                lambda trade, symbol=symbol: str(trade.get("symbol") or "") == symbol,
            )
        )
    for family in families:
        specs.append(
            (
                f"family_{_slug(family)}",
                {"dominant_factor_family": family},
                lambda trade, family=family: _trade_factor_family(trade) == family,
            )
        )
    for threshold in (1.0, 1.5, 2.0, 2.5, 3.0):
        specs.append(
            (
                f"abs_score_ge_{threshold:g}",
                {"abs_factor_score_min": threshold},
                lambda trade, threshold=threshold: _trade_abs_factor_score(trade) >= threshold,
            )
        )
    for max_hold in (4, 8, 12, 24, 48, 72):
        specs.append(
            (
                f"max_hold_le_{max_hold}h",
                {"max_hold_hours": max_hold},
                lambda trade, max_hold=max_hold: _trade_hold_hours(trade) <= max_hold,
            )
        )
    for side in ("LONG", "SHORT"):
        for threshold in (1.0, 1.5, 2.0, 2.5):
            specs.append(
                (
                    f"side_{side.lower()}_abs_score_ge_{threshold:g}",
                    {"side": side, "abs_factor_score_min": threshold},
                    lambda trade, side=side, threshold=threshold: str(trade.get("side") or "") == side
                    and _trade_abs_factor_score(trade) >= threshold,
                )
            )
    for family in families:
        for threshold in (1.0, 1.5, 2.0, 2.5):
            specs.append(
                (
                    f"family_{_slug(family)}_abs_score_ge_{threshold:g}",
                    {"dominant_factor_family": family, "abs_factor_score_min": threshold},
                    lambda trade, family=family, threshold=threshold: _trade_factor_family(trade) == family
                    and _trade_abs_factor_score(trade) >= threshold,
                )
            )
    for side in ("LONG", "SHORT"):
        for family in families:
            specs.append(
                (
                    f"side_{side.lower()}_family_{_slug(family)}",
                    {"side": side, "dominant_factor_family": family},
                    lambda trade, side=side, family=family: str(trade.get("side") or "") == side
                    and _trade_factor_family(trade) == family,
                )
            )
    for side in ("LONG", "SHORT"):
        for symbol in symbols:
            specs.append(
                (
                    f"side_{side.lower()}_symbol_{_slug(symbol)}",
                    {"side": side, "symbol": symbol},
                    lambda trade, side=side, symbol=symbol: str(trade.get("side") or "") == side
                    and str(trade.get("symbol") or "") == symbol,
                )
            )
    return specs


def _variant_selection_key(summary: Mapping[str, Any]) -> tuple[float, float, float, str]:
    """Train+validation-only key; locked-OOS is deliberately excluded."""
    validation = dict(summary.get("validation") or {})
    train = dict(summary.get("train") or {})
    return (
        _safe_float(summary.get("train_validation_score")),
        _safe_float(validation.get("total_return")),
        _safe_float(train.get("total_return")),
        str(summary.get("model_id") or ""),
    )


def _maybe_keep_top_variant(
    heap: list[tuple[tuple[float, float, float, str], int, dict[str, Any]]],
    *,
    limit: int,
    serial: int,
    record: Mapping[str, Any],
) -> None:
    if limit <= 0:
        return
    key = _variant_selection_key(dict(record.get("summary") or {}))
    item = (key, serial, dict(record))
    if len(heap) < limit:
        heapq.heappush(heap, item)
        return
    if item[0] > heap[0][0]:
        heapq.heapreplace(heap, item)


def _fresh_train_validation_retune(
    args: argparse.Namespace,
    *,
    source_live_payload: Mapping[str, Any],
    source_candidate_rows: Sequence[Mapping[str, Any]],
) -> dict[str, Any]:
    """Recompute TV-frozen Alpha Zoo candidates under the primary 10bps cost.

    The source candidate CSV was generated by the high-leverage lane with
    train+validation ranking before locked-OOS gates were attached.  This step
    replays those candidate trades at 10bps, then re-ranks only train+validation
    cost-adjusted metrics.  Locked-OOS metrics are attached only after the fresh
    10bps candidate rows and hybrid inputs are frozen.
    """
    selected_rows = _candidate_rows_for_fresh_retune(
        source_candidate_rows,
        limit=_safe_int(getattr(args, "fresh_candidate_limit", 0), 0),
    )
    if not selected_rows:
        return {
            "metric_rows": [],
            "summaries": [],
            "hybrid_weights": [],
            "hybrid_results": {},
            "variant_inventory_rows": [],
            "selected_source_rows": 0,
            "evaluated_streams": 0,
            "evaluated_trade_filter_variants": 0,
            "selected_trade_filter_variants": 0,
            "trade_filter_gate_pass_count": 0,
            "skipped_candidate_names": [],
        }

    runtime = cost._build_alpha_runtime(args, source_live_payload)
    alpha = runtime["alpha"]
    specs = cost._spec_by_name(alpha, runtime["old_replay"])
    available_rows: list[dict[str, Any]] = []
    skipped_names: set[str] = set()
    for row in selected_rows:
        name = str(row.get("candidate_name") or "")
        if name in specs:
            available_rows.append(dict(row))
        else:
            skipped_names.add(name)
    trade_cache = cost._build_trade_cache(
        alpha=alpha,
        data=runtime["data"],
        calibrated_edges=runtime["calibrated_edges"],
        specs=specs,
        candidate_names=[row["candidate_name"] for row in available_rows],
    )

    metric_rows: list[dict[str, Any]] = []
    summaries: list[dict[str, Any]] = []
    stream_records: list[dict[str, Any]] = []
    variant_inventory_rows: list[dict[str, Any]] = []
    variant_top_heap: list[tuple[tuple[float, float, float, str], int, dict[str, Any]]] = []
    variant_gate_pass_records: dict[str, dict[str, Any]] = {}
    evaluated_trade_filter_variants = 0
    trade_filter_gate_pass_count = 0
    variant_serial = 0
    enable_trade_filter_variants = not bool(getattr(args, "disable_trade_filter_variants", False))
    trade_filter_top_n = max(0, _safe_int(getattr(args, "trade_filter_top_n", 0), 0))
    min_trade_filter_trades = max(1, _safe_int(getattr(args, "min_trade_filter_trades", 20), 20))
    for source_row in available_rows:
        candidate_name = str(source_row.get("candidate_name") or "")
        leverage = _safe_float(source_row.get("leverage"))
        allocation = _safe_float(source_row.get("allocation_fraction"))
        cache = trade_cache[candidate_name]
        trades = list(cache["trades"])
        stream = cost._stream_from_trades(
            alpha=alpha,
            trades=trades,
            timestamps=runtime["timestamps"],
            ts_to_idx=runtime["ts_to_idx"],
            split_masks=runtime["split_masks"],
            candidate_row=source_row,
            round_trip_slippage_bps=PRIMARY_COST_BPS,
        )
        split_metrics = dict(stream.get("split_metrics") or {})
        score = _train_validation_score(split_metrics)
        gate = _promotion_gate_result(
            split_metrics,
            cost_bps=PRIMARY_COST_BPS,
            candidate_universe_uses_locked_oos_bucket=False,
            regenerated_train_validation_only=True,
            promotability_scope="live_candidate",
            strict_zero_liquidation=True,
        )
        model_id = _fresh_model_id("fresh_tv10_seed", source_row)
        summaries.append(
            _summary_from_split_metrics(
                model_id=model_id,
                model_kind="individual_seed",
                role="fresh_train_validation_10bps_retune",
                split_metrics=split_metrics,
                score=score,
                gate=gate,
                candidate_name=candidate_name,
                leverage=leverage,
                allocation_fraction=allocation,
            )
        )
        metric_rows.extend(
            _metric_rows_from_split_metrics(
                model_id=model_id,
                model_kind="individual_seed",
                role="fresh_train_validation_10bps_retune",
                split_metrics=split_metrics,
                score=score,
                gate=gate,
                candidate_name=candidate_name,
                leverage=leverage,
                allocation_fraction=allocation,
                strict_zero_liquidation=True,
            )
        )
        stream_records.append({"stream": stream, "summary": summaries[-1]})
        if not enable_trade_filter_variants:
            continue
        for variant_name, variant_params, predicate in _trade_filter_variant_specs(trades):
            filtered_trades = [trade for trade in trades if predicate(trade)]
            if len(filtered_trades) < min_trade_filter_trades:
                continue
            evaluated_trade_filter_variants += 1
            variant_stream = cost._stream_from_trades(
                alpha=alpha,
                trades=filtered_trades,
                timestamps=runtime["timestamps"],
                ts_to_idx=runtime["ts_to_idx"],
                split_masks=runtime["split_masks"],
                candidate_row=source_row,
                round_trip_slippage_bps=PRIMARY_COST_BPS,
            )
            variant_split_metrics = dict(variant_stream.get("split_metrics") or {})
            variant_score = _train_validation_score(variant_split_metrics)
            variant_gate = _promotion_gate_result(
                variant_split_metrics,
                cost_bps=PRIMARY_COST_BPS,
                candidate_universe_uses_locked_oos_bucket=False,
                regenerated_train_validation_only=True,
                promotability_scope="live_candidate",
                strict_zero_liquidation=True,
            )
            if variant_gate["primary_10bps_promotion_gate_pass"]:
                trade_filter_gate_pass_count += 1
            variant_model_id = _fresh_model_id(f"fresh_tv10_filter_{_slug(variant_name)}", source_row)
            extra_fields = {
                "variant_name": variant_name,
                "trade_filter_params": dict(variant_params),
                "filter_trade_count": len(filtered_trades),
            }
            variant_summary = _summary_from_split_metrics(
                model_id=variant_model_id,
                model_kind="individual_seed_trade_filter",
                role="fresh_train_validation_10bps_trade_filter",
                split_metrics=variant_split_metrics,
                score=variant_score,
                gate=variant_gate,
                candidate_name=candidate_name,
                leverage=leverage,
                allocation_fraction=allocation,
                extra_fields=extra_fields,
            )
            variant_record = {
                "summary": variant_summary,
                "split_metrics": variant_split_metrics,
                "gate": variant_gate,
                "stream": variant_stream,
                "extra_fields": extra_fields,
                "candidate_name": candidate_name,
                "leverage": leverage,
                "allocation_fraction": allocation,
                "variant_model_id": variant_model_id,
            }
            variant_serial += 1
            _maybe_keep_top_variant(
                variant_top_heap,
                limit=trade_filter_top_n,
                serial=variant_serial,
                record=variant_record,
            )
            if variant_gate["primary_10bps_promotion_gate_pass"]:
                variant_gate_pass_records[variant_model_id] = variant_record

    selected_variant_records: dict[str, dict[str, Any]] = {
        str(record["variant_model_id"]): record for _key, _serial, record in variant_top_heap
    }
    selected_variant_records.update(variant_gate_pass_records)
    for record in sorted(
        selected_variant_records.values(),
        key=lambda item: _variant_selection_key(dict(item.get("summary") or {})),
        reverse=True,
    ):
        summary = dict(record["summary"])
        split_metrics = dict(record["split_metrics"])
        gate = dict(record["gate"])
        extra_fields = dict(record["extra_fields"])
        model_id = str(record["variant_model_id"])
        summaries.append(summary)
        metric_rows.extend(
            _metric_rows_from_split_metrics(
                model_id=model_id,
                model_kind="individual_seed_trade_filter",
                role="fresh_train_validation_10bps_trade_filter",
                split_metrics=split_metrics,
                score=_safe_float(summary.get("train_validation_score")),
                gate=gate,
                candidate_name=str(record.get("candidate_name") or ""),
                leverage=_safe_float(record.get("leverage")),
                allocation_fraction=_safe_float(record.get("allocation_fraction")),
                strict_zero_liquidation=True,
                extra_fields=extra_fields,
            )
        )
        stream_records.append({"stream": dict(record["stream"]), "summary": summary})
        variant_inventory_rows.append(
            _variant_row(
                candidate_name=str(record.get("candidate_name") or ""),
                variant_name=str(extra_fields.get("variant_name") or ""),
                params={
                    **dict(extra_fields.get("trade_filter_params") or {}),
                    "filter_trade_count": int(extra_fields.get("filter_trade_count") or 0),
                    "selection_inputs": list(TV_SPLITS),
                    "round_trip_slippage_fee_bps": PRIMARY_COST_BPS,
                },
                source="fresh_train_validation_trade_filter_grid",
            )
        )

    ranked_records = sorted(
        stream_records,
        key=lambda item: _safe_float(item["summary"].get("train_validation_score")),
        reverse=True,
    )
    hybrid_seed_count = max(0, _safe_int(getattr(args, "hybrid_seed_count", 0), 0))
    hybrid_records = ranked_records[:hybrid_seed_count]
    hybrid_weights: list[dict[str, Any]] = []
    hybrid_results: dict[str, Any] = {}
    if len(hybrid_records) >= 2 and _safe_int(getattr(args, "n_trials", 0), 0) > 0:
        seed_streams = [dict(item["stream"]) for item in hybrid_records]
        returns = np.column_stack(
            [np.asarray(stream["returns"], dtype=float) for stream in seed_streams]
        )
        labels = [str(stream["label"]) for stream in seed_streams]
        for model_id, version in (
            ("hybrid_v3_5_fresh_tv10", "v3_5"),
            ("hybrid_v3_6_fresh_tv10", "v3_6"),
        ):
            result = cost.hybrid._run_optuna(
                returns,
                runtime["split_masks"],
                version=version,
                n_trials=_safe_int(getattr(args, "n_trials", 0), 0),
                seed=_safe_int(getattr(args, "seed", 20260519), 20260519),
            )
            public = cost._public_hybrid_result(
                result,
                labels=labels,
                returns=returns,
                split_masks=runtime["split_masks"],
                timestamps=runtime["timestamps"],
                streams=seed_streams,
            )
            public.pop("portfolio_returns", None)
            split_metrics = dict(public.get("splits") or {})
            score = _train_validation_score(split_metrics)
            gate = _promotion_gate_result(
                split_metrics,
                cost_bps=PRIMARY_COST_BPS,
                candidate_universe_uses_locked_oos_bucket=False,
                regenerated_train_validation_only=True,
                promotability_scope="live_candidate",
                strict_zero_liquidation=True,
            )
            hybrid_results[model_id] = public
            summaries.append(
                _summary_from_split_metrics(
                    model_id=model_id,
                    model_kind="hybrid",
                    role="fresh_train_validation_10bps_hybrid",
                    split_metrics=split_metrics,
                    score=score,
                    gate=gate,
                )
            )
            metric_rows.extend(
                _metric_rows_from_split_metrics(
                    model_id=model_id,
                    model_kind="hybrid",
                    role="fresh_train_validation_10bps_hybrid",
                    split_metrics=split_metrics,
                    score=score,
                    gate=gate,
                    strict_zero_liquidation=True,
                )
            )
            for label, weight in dict(public.get("final_weight_by_candidate") or {}).items():
                hybrid_weights.append(
                    {
                        "round_trip_slippage_fee_bps": PRIMARY_COST_BPS,
                        "model_id": model_id,
                        "candidate_label": label,
                        "weight": float(weight),
                    }
                )
    return {
        "metric_rows": metric_rows,
        "summaries": summaries,
        "hybrid_weights": hybrid_weights,
        "hybrid_results": hybrid_results,
        "variant_inventory_rows": variant_inventory_rows,
        "selected_source_rows": len(selected_rows),
        "evaluated_streams": len(stream_records),
        "evaluated_trade_filter_variants": evaluated_trade_filter_variants,
        "selected_trade_filter_variants": len(selected_variant_records),
        "trade_filter_gate_pass_count": trade_filter_gate_pass_count,
        "skipped_candidate_names": sorted(skipped_names),
    }


def _metric_rows_with_primary_gates(
    grouped: Mapping[str, Sequence[Mapping[str, Any]]],
    *,
    source_payload: Mapping[str, Any],
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    all_rows: list[dict[str, Any]] = []
    summaries: list[dict[str, Any]] = []
    shadow_only = _source_rows_are_shadow_only(source_payload)
    for model_id, rows in sorted(grouped.items()):
        split_metrics = _split_metrics_from_rows(rows)
        score = _train_validation_score(split_metrics)
        gate = _promotion_gate_result(
            split_metrics,
            cost_bps=PRIMARY_COST_BPS,
            candidate_universe_uses_locked_oos_bucket=shadow_only,
            regenerated_train_validation_only=not shadow_only,
            promotability_scope="shadow_only" if shadow_only else "live_candidate",
            strict_zero_liquidation=True,
        )
        identity = _model_identity(rows)
        summary = {
            **identity,
            **gate,
            "train_validation_score": score,
            "shadow_only": gate["promotability_scope"] == "shadow_only",
            "train": split_metrics.get("train", {}),
            "validation": split_metrics.get("validation", {}),
            "locked_oos": split_metrics.get("locked_oos", {}),
        }
        summaries.append(summary)
        for row in sorted(rows, key=lambda item: SPLIT_ORDER.index(str(item.get("split")))):
            all_rows.append(
                {
                    **dict(row),
                    **{
                        "round_trip_slippage_fee_bps": PRIMARY_COST_BPS,
                        "train_validation_score": score,
                        "candidate_universe_uses_locked_oos_bucket": gate[
                            "candidate_universe_uses_locked_oos_bucket"
                        ],
                        "regenerated_train_validation_only": gate[
                            "regenerated_train_validation_only"
                        ],
                        "promotability_scope": gate["promotability_scope"],
                        "shadow_only": summary["shadow_only"],
                        "calendar_primary": False,
                        "primary_10bps_promotion_gate_pass": gate[
                            "primary_10bps_promotion_gate_pass"
                        ],
                        "primary_10bps_promotion_gate_reasons": ";".join(
                            gate["primary_10bps_promotion_gate_reasons"]
                        ),
                        "live_promotable_10bps": gate["live_promotable_10bps"],
                    },
                }
            )
    return all_rows, summaries


def _execution_cost_evidence() -> dict[str, Any]:
    return {
        "diagnostic_only": True,
        "symbols": list(EXECUTION_COST_SYMBOLS),
        "primary_round_trip_cost_bps": PRIMARY_COST_BPS,
        "promotion_baseline_locked": True,
        "may_reduce_promotion_cost": False,
        "source_note": (
            "Execution-cost context is diagnostic only; promotion remains locked to "
            "10bps all-in round-trip slippage/fee."
        ),
        "snapshot_status": "not_required_for_local_gate_tests",
        "collected_at_utc": _utc_now_iso(),
    }


def _memory_summary() -> dict[str, Any]:
    peak = _rss_mib()
    passed = peak < MEMORY_LIMIT_MIB
    return {
        "limit_mib": MEMORY_LIMIT_MIB,
        "peak_rss_mib": peak,
        "pass_under_8gb": passed,
        "guard_status": "pass" if passed else "fail",
        "pass_fail_reason": (
            f"peak_rss_mib={peak:.1f} below limit_mib={MEMORY_LIMIT_MIB:.1f}"
            if passed
            else f"peak_rss_mib={peak:.1f} exceeded limit_mib={MEMORY_LIMIT_MIB:.1f}"
        ),
    }


def _locked_oos_contamination_audit() -> dict[str, Any]:
    return {
        "uses_locked_oos_for_objective": False,
        "uses_locked_oos_for_pruning": False,
        "uses_locked_oos_for_selection": False,
        "uses_locked_oos_for_parameter_fitting": False,
        "locked_oos_role": "gate_report_only_after_candidate_freeze",
        "evidence": [
            "train_validation_score reads train and validation metrics only",
            "primary promotion gate reads locked-OOS only after model rows are frozen",
            "historical OOS/top-bucket seed-union rows are marked shadow_only",
        ],
    }


def _validate_split_manifest(payload: Mapping[str, Any], *, allow_split_hash_drift: bool) -> dict[str, Any]:
    split_manifest = dict(payload.get("split_manifest") or {})
    observed_hash = str(split_manifest.get("timestamp_index_hash") or "")
    if observed_hash != EXPECTED_TIMESTAMP_INDEX_HASH and not allow_split_hash_drift:
        raise ValueError(
            "split timestamp hash drift: "
            f"observed={observed_hash!r} expected={EXPECTED_TIMESTAMP_INDEX_HASH!r}"
        )
    return split_manifest


def _best_model(
    summaries: Sequence[Mapping[str, Any]],
    *,
    require_live_promotable: bool,
) -> dict[str, Any] | None:
    candidates = [
        dict(item)
        for item in summaries
        if (not require_live_promotable or _as_bool(item.get("live_promotable_10bps")))
    ]
    if not candidates:
        return None
    return sorted(
        candidates,
        key=lambda row: (
            _as_bool(row.get("live_promotable_10bps")),
            _safe_float(row.get("train_validation_score")),
            _safe_float(dict(row.get("locked_oos") or {}).get("total_return")),
            str(row.get("model_id") or ""),
        ),
        reverse=True,
    )[0]


def build_payload(args: argparse.Namespace) -> dict[str, Any]:
    source_cost_json = Path(
        getattr(args, "source_cost_json", getattr(args, "cost_validation_json", DEFAULT_SOURCE_COST_JSON))
    ).expanduser().resolve()
    source_cost_metrics_csv = Path(
        getattr(args, "source_cost_metrics_csv", DEFAULT_SOURCE_COST_METRICS_CSV)
    ).expanduser().resolve()
    source_live_json = Path(getattr(args, "source_live_json", DEFAULT_SOURCE_LIVE_JSON)).expanduser().resolve()
    source_candidate_csv = Path(
        getattr(args, "source_candidate_csv", getattr(args, "candidate_csv", DEFAULT_SOURCE_CANDIDATE_CSV))
    ).expanduser().resolve()
    source_payload = _load_json(source_cost_json)
    source_live_payload = _load_json(source_live_json)
    source_candidate_rows = _read_csv(source_candidate_csv) if source_candidate_csv.exists() else []
    split_manifest = _validate_split_manifest(
        source_payload,
        allow_split_hash_drift=bool(getattr(args, "allow_split_hash_drift", False)),
    )
    source_rows = _load_source_metric_rows(source_payload, source_cost_metrics_csv)
    grouped = _group_metric_rows_by_model(source_rows)
    shadow_metric_rows, shadow_summaries = _metric_rows_with_primary_gates(
        grouped,
        source_payload=source_payload,
    )
    fresh_retune = _fresh_train_validation_retune(
        args,
        source_live_payload=source_live_payload,
        source_candidate_rows=source_candidate_rows,
    )
    metric_rows = [*list(fresh_retune["metric_rows"]), *shadow_metric_rows]
    summaries = [*list(fresh_retune["summaries"]), *shadow_summaries]
    variant_inventory = [
        *_build_variant_inventory(source_live_payload),
        *list(fresh_retune.get("variant_inventory_rows") or []),
    ]
    fresh_summaries = [
        dict(item)
        for item in list(fresh_retune["summaries"])
        if not _as_bool(dict(item).get("shadow_only"))
    ]
    live_model = _best_model(fresh_summaries, require_live_promotable=True)
    best_fresh = _best_model(fresh_summaries, require_live_promotable=False)
    best_shadow = _best_model(shadow_summaries, require_live_promotable=False)
    execution_cost = _execution_cost_evidence()
    return {
        "artifact_kind": "alpha_zoo_10bps_full_retune",
        "generated_at_utc": _utc_now_iso(),
        "real_money_execution": False,
        "round_trip_slippage_fee_bps_primary": PRIMARY_COST_BPS,
        "split_manifest": split_manifest,
        "source_inputs": {
            "source_cost_json": str(source_cost_json),
            "source_cost_metrics_csv": str(source_cost_metrics_csv),
            "source_live_json": str(source_live_json),
            "source_candidate_csv": str(source_candidate_csv),
        },
        "method_contract": {
            "runner_lane": "candidate_and_cost_promotion_gates",
            "primary_cost_only_for_promotion": PRIMARY_COST_BPS,
            "n_trials_requested": int(getattr(args, "n_trials", 0)),
            "source_cost_rows": len(source_rows),
            "shadow_primary_10bps_metric_rows": len(shadow_metric_rows),
            "fresh_primary_10bps_metric_rows": len(list(fresh_retune["metric_rows"])),
            "primary_10bps_metric_rows": len(metric_rows),
            "candidate_csv_rows_seen": len(source_candidate_rows),
            "variant_inventory_rows": len(variant_inventory),
            "historical_top_bucket_rows_shadow_only": _source_rows_are_shadow_only(source_payload),
            "fresh_train_validation_retune": {
                "selection_inputs": list(TV_SPLITS),
                "uses_locked_oos_for_selection": False,
                "candidate_rows_selected_before_oos_gate": fresh_retune["selected_source_rows"],
                "evaluated_10bps_streams": fresh_retune["evaluated_streams"],
                "evaluated_trade_filter_variants": fresh_retune[
                    "evaluated_trade_filter_variants"
                ],
                "selected_trade_filter_variants": fresh_retune[
                    "selected_trade_filter_variants"
                ],
                "trade_filter_gate_pass_count": fresh_retune["trade_filter_gate_pass_count"],
                "trade_filter_selection_inputs": list(TV_SPLITS),
                "trade_filter_locked_oos_role": "gate_report_only_after_variant_freeze",
                "skipped_candidate_names": fresh_retune["skipped_candidate_names"],
            },
        },
        "selection_policy": {
            "selection_inputs": list(TV_SPLITS),
            "optimization_input_splits": list(TV_SPLITS),
            "hybrid_selection_inputs": list(TV_SPLITS),
            "uses_locked_oos_for_objective": False,
            "uses_locked_oos_for_pruning": False,
            "uses_locked_oos_for_selection": False,
            "uses_locked_oos_for_parameter_fitting": False,
            "locked_oos_role": "gate_report_only_after_candidate_freeze",
        },
        "candidate_universe_summary": {
            "model_count": len(summaries),
            "fresh_train_validation_model_count": len(fresh_summaries),
            "fresh_trade_filter_model_count": sum(
                1
                for item in fresh_summaries
                if str(item.get("role") or "") == "fresh_train_validation_10bps_trade_filter"
            ),
            "primary_10bps_models": sorted(grouped),
            "live_promotable_count": sum(
                1 for item in summaries if _as_bool(item.get("live_promotable_10bps"))
            ),
            "shadow_only_count": sum(1 for item in summaries if _as_bool(item.get("shadow_only"))),
        },
        "locked_oos_contamination_audit": _locked_oos_contamination_audit(),
        "execution_cost_evidence": execution_cost,
        "memory_summary": _memory_summary(),
        "model_gate_summaries": summaries,
        "candidate_model_metrics": metric_rows,
        "candidate_variant_inventory": variant_inventory,
        "tuned_seed_selection": {
            "selection_inputs": list(TV_SPLITS),
            "uses_locked_oos_for_selection": False,
            "primary_cost_bps": PRIMARY_COST_BPS,
            "rows": sorted(
                fresh_summaries,
                key=lambda row: _safe_float(row.get("train_validation_score")),
                reverse=True,
            )[: int(getattr(args, "top_n", 50))],
            "shadow_reference_rows": sorted(
                shadow_summaries,
                key=lambda row: _safe_float(row.get("train_validation_score")),
                reverse=True,
            )[: int(getattr(args, "top_n", 50))],
        },
        "fresh_hybrid_results_10bps": fresh_retune["hybrid_results"],
        "hybrid_weights_10bps": list(fresh_retune["hybrid_weights"]) or [
            dict(row)
            for row in list(source_payload.get("hybrid_weights") or [])
            if math.isclose(_safe_float(dict(row).get("round_trip_slippage_fee_bps")), PRIMARY_COST_BPS)
        ],
        "live_promotable_10bps_model_id": None if live_model is None else live_model.get("model_id"),
        "no_10bps_live_ready_model": live_model is None,
        "best_fresh_10bps_model": best_fresh or {},
        "best_shadow_10bps_model": best_shadow or {},
    }


def _markdown(payload: Mapping[str, Any]) -> str:
    split_manifest = dict(payload.get("split_manifest") or {})
    summary = dict(payload.get("candidate_universe_summary") or {})
    best = dict(payload.get("best_shadow_10bps_model") or {})
    lines = [
        "# Alpha Zoo 10bps full-retune gate artifact",
        "",
        f"Generated: `{payload.get('generated_at_utc')}`",
        f"Primary round-trip cost: `{payload.get('round_trip_slippage_fee_bps_primary')} bps`",
        f"Real-money execution: `{payload.get('real_money_execution')}`",
        f"Timestamp hash: `{split_manifest.get('timestamp_index_hash')}`",
        "",
        "## Candidate universe",
        "",
        f"- model count: `{summary.get('model_count')}`",
        f"- primary 10bps metric rows: `{dict(payload.get('method_contract') or {}).get('primary_10bps_metric_rows')}`",
        f"- live promotable count: `{summary.get('live_promotable_count')}`",
        f"- shadow-only count: `{summary.get('shadow_only_count')}`",
        "",
        "## Live readiness",
        "",
    ]
    if payload.get("live_promotable_10bps_model_id"):
        lines.append(f"- live-promotable model: `{payload.get('live_promotable_10bps_model_id')}`")
    else:
        lines.append("- no 10bps live-ready model passed all promotion gates.")
    if best:
        lines.extend(
            [
                f"- best shadow model: `{best.get('model_id')}`",
                f"- best shadow train+validation score: `{_safe_float(best.get('train_validation_score')):.6f}`",
                "- best shadow rejection reasons: "
                f"`{';'.join(best.get('primary_10bps_promotion_gate_reasons') or [])}`",
            ]
        )
    lines.extend(["", "## Output paths", ""])
    for key, value in dict(payload.get("output_paths") or {}).items():
        lines.append(f"- {key}: `{value}`")
    return "\n".join(lines) + "\n"


def write_outputs(payload: Mapping[str, Any], output_dir: Path) -> dict[str, str]:
    output_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
    latest_json = output_dir / "alpha_zoo_10bps_full_retune_latest.json"
    timestamped_json = output_dir / f"alpha_zoo_10bps_full_retune_{timestamp}.json"
    latest_md = output_dir / "alpha_zoo_10bps_full_retune_latest.md"
    timestamped_md = output_dir / f"alpha_zoo_10bps_full_retune_{timestamp}.md"
    metrics_csv = output_dir / "candidate_model_metrics_latest.csv"
    variants_csv = output_dir / "candidate_variant_inventory_latest.csv"
    seed_json = output_dir / "tuned_seed_selection_latest.json"
    seed_csv = output_dir / "tuned_seed_selection_latest.csv"
    weights_csv = output_dir / "hybrid_weights_latest.csv"
    cost_json = output_dir / "execution_cost_evidence_latest.json"
    output_paths = {
        "latest_json": str(latest_json),
        "timestamped_json": str(timestamped_json),
        "latest_markdown": str(latest_md),
        "timestamped_markdown": str(timestamped_md),
        "candidate_model_metrics_csv": str(metrics_csv),
        "candidate_variant_inventory_csv": str(variants_csv),
        "tuned_seed_selection_json": str(seed_json),
        "tuned_seed_selection_csv": str(seed_csv),
        "hybrid_weights_csv": str(weights_csv),
        "execution_cost_evidence_json": str(cost_json),
    }
    payload = {**dict(payload), "output_paths": output_paths}
    _write_json(latest_json, payload)
    _write_json(timestamped_json, payload)
    _write_json(seed_json, dict(payload.get("tuned_seed_selection") or {}))
    _write_json(cost_json, dict(payload.get("execution_cost_evidence") or {}))
    latest_md.write_text(_markdown(payload), encoding="utf-8")
    timestamped_md.write_text(_markdown(payload), encoding="utf-8")
    metric_fields = [
        "model_id",
        "model_kind",
        "role",
        "candidate_name",
        "variant_name",
        "leverage",
        "allocation_fraction",
        "round_trip_slippage_fee_bps",
        "split",
        "total_return",
        "max_drawdown",
        "sharpe",
        "sortino",
        "smart_sortino",
        "calmar",
        "return_mdd",
        "trade_event_count",
        "active_return_hours",
        "liquidation_count",
        "account_wipeout_count",
        "minimum_margin_buffer",
        "split_gate_pass",
        "split_gate_reasons",
        "locked_oos_deployable_gate_pass",
        "locked_oos_deployable_gate_reasons",
        "train_validation_score",
        "filter_trade_count",
        "trade_filter_params",
        "candidate_universe_uses_locked_oos_bucket",
        "regenerated_train_validation_only",
        "promotability_scope",
        "shadow_only",
        "calendar_primary",
        "primary_10bps_promotion_gate_pass",
        "primary_10bps_promotion_gate_reasons",
        "live_promotable_10bps",
    ]
    variant_fields = [
        "candidate_name",
        "variant_name",
        "source",
        "calendar_primary",
        "calendar_rule_rejection_reasons",
        "variant_gate_pass",
        "params_json",
    ]
    seed_fields = [
        "model_id",
        "model_kind",
        "role",
        "candidate_name",
        "variant_name",
        "leverage",
        "allocation_fraction",
        "round_trip_slippage_fee_bps",
        "train_validation_score",
        "filter_trade_count",
        "trade_filter_params",
        "promotability_scope",
        "shadow_only",
        "primary_10bps_promotion_gate_pass",
        "primary_10bps_promotion_gate_reasons",
        "live_promotable_10bps",
    ]
    _write_csv(metrics_csv, list(payload.get("candidate_model_metrics") or []), metric_fields)
    _write_csv(variants_csv, list(payload.get("candidate_variant_inventory") or []), variant_fields)
    _write_csv(
        seed_csv,
        list(dict(payload.get("tuned_seed_selection") or {}).get("rows") or []),
        seed_fields,
    )
    _write_csv(
        weights_csv,
        list(payload.get("hybrid_weights_10bps") or []),
        ["round_trip_slippage_fee_bps", "model_id", "candidate_label", "weight"],
    )
    return output_paths


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-cost-json", default=str(DEFAULT_SOURCE_COST_JSON))
    parser.add_argument("--source-cost-metrics-csv", default=str(DEFAULT_SOURCE_COST_METRICS_CSV))
    parser.add_argument("--source-live-json", default=str(DEFAULT_SOURCE_LIVE_JSON))
    parser.add_argument("--source-candidate-csv", default=str(DEFAULT_SOURCE_CANDIDATE_CSV))
    parser.add_argument("--output-dir", default=str(DEFAULT_OUTPUT_DIR))
    parser.add_argument("--n-trials", type=int, default=80)
    parser.add_argument("--top-n", type=int, default=50)
    parser.add_argument("--allow-split-hash-drift", action="store_true")
    parser.add_argument("--fresh-candidate-limit", type=int, default=80)
    parser.add_argument("--hybrid-seed-count", type=int, default=8)
    parser.add_argument("--trade-filter-top-n", type=int, default=120)
    parser.add_argument("--min-trade-filter-trades", type=int, default=20)
    parser.add_argument("--disable-trade-filter-variants", action="store_true")
    parser.add_argument("--seed", type=int, default=20260519)
    parser.add_argument("--input", default="")
    parser.add_argument("--current-tail-cache", default=str(high.DEFAULT_CURRENT_TAIL_CACHE))
    parser.add_argument("--external-state-csv", default=str(high.DEFAULT_EXTERNAL_STATE_CSV))
    parser.add_argument("--old-alpha-replay-json", default=str(high.DEFAULT_OLD_ALPHA_REPLAY))
    parser.add_argument("--alpha-calibration-json", default="")
    parser.add_argument("--train-start", default=high.DEFAULT_TRAIN_START)
    parser.add_argument("--train-end", default=high.DEFAULT_TRAIN_END)
    parser.add_argument("--validation-start", default=high.DEFAULT_VALIDATION_START)
    parser.add_argument("--validation-end", default=high.DEFAULT_VALIDATION_END)
    parser.add_argument("--locked-oos-start", default=high.DEFAULT_LOCKED_OOS_START)
    parser.add_argument("--locked-oos-end", default=high.DEFAULT_LOCKED_OOS_END)
    parser.add_argument("--horizon", type=int, default=high.DEFAULT_HORIZON)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    output_dir = Path(args.output_dir).expanduser().resolve()
    payload = build_payload(args)
    outputs = write_outputs(payload, output_dir)
    print(
        json.dumps(
            {
                **outputs,
                "model_count": dict(payload.get("candidate_universe_summary") or {}).get(
                    "model_count"
                ),
                "live_promotable_10bps_model_id": payload.get("live_promotable_10bps_model_id"),
                "no_10bps_live_ready_model": payload.get("no_10bps_live_ready_model"),
                "peak_rss_mib": dict(payload.get("memory_summary") or {}).get("peak_rss_mib"),
            },
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
